class dofus.§\x1e\x13\x12§ extends §\x19\x04§.§\x1a\x05\x14§.§\x1b\x13\x13§
{
   function §\x1e\x13\x12§(§\x1c\x1e\x1d§)
   {
      super();
      System.security.allowDomain("*");
      getURL("FSCommand:" add "trapallkeys","true");
      dofus["\x1e\x13\x12"]._mcCore = _loc3_;
      dofus["\x1e\x13\x12"]._cCore = this;
      _global["\x1a\x10\x19"] = trace;
   }
   static function §\x1e\x07\x12§()
   {
      if(_root.CORECONTAINER == undefined)
      {
         _root.createEmptyMovieClip("CORECONTAINER",_root.getNextHighestDepth());
      }
      return _root.CORECONTAINER;
   }
   static function §\x1e\x03\x15§()
   {
      return dofus["\x1e\x13\x12"]._cCore;
   }
   function §\x1d\x12\r§()
   {
      this["\x1b\x11\r"]();
      eval("\x19\x04")["\x1a\x05\x14"]["\x1e\x0e\x10"]["\x1d\x14"]();
      this["\x1b\x1c"]({object:this,method:this["\x1d\x01"]});
   }
   function §\x1d\x01§()
   {
      var _loc2_ = dofus["\x1e\x13\x12"]["\x1e\x07\x12"]();
      this["\x18\x0b\x18"] = _loc2_.createEmptyMovieClip("\x1a\r\x11",_loc2_.getNextHighestDepth());
      this["\x18\x0b\x18"]._visible = false;
      _loc2_.attachMovie("BATTLEFIELD","BATTLEFIELD",_loc2_.getNextHighestDepth());
      _loc2_.attachMovie("GAPIMain","GAPI",_loc2_.getNextHighestDepth());
      _loc2_.attachMovie("mask","MASK",_loc2_.getNextHighestDepth());
      this["\x1b\x1c"]({object:this,method:this["\x1d\x13\x15"]});
   }
   function §\x1d\x13\x15§()
   {
      _global["\x18\x1b"] = new dofus["\x1a\x05\x14"]["\x18\x1c"]();
      _global["\x18\x1b"].initialize();
      this["\x1b\x1c"]({object:this,method:this["\x02\n"]});
   }
   function §\x02\n§()
   {
      if(this["\x02\x0b"]())
      {
         this["\x1a\x13\n"]();
      }
      else
      {
         this["\x1b\x1c"]({object:this,method:this["\x02\n"]});
      }
   }
   function §\x02\x0b§()
   {
      if(_global["\x18\x1b"].gfx.initialize == undefined)
      {
         return false;
      }
      if(_global["\x18\x1b"]["\x1d\x0b\x04"].start == undefined)
      {
         return false;
      }
      if(_global["\x18\x1b"].ui["\x1d\x06\x04"] == undefined)
      {
         return false;
      }
      return true;
   }
   function §\x1a\x13\n§()
   {
      _global["\x18\x1b"]["\x1d\x0b\x04"].start();
   }
   function §\x1e\n\x18§()
   {
      var _loc2_ = dofus["\x1e\x13\x12"]["\x1e\x07\x12"]();
      _loc2_.attachMovie("clipForceOver","_mcForceOver",1000,{_x:_loc2_._xmouse,_y:_loc2_._ymouse});
   }
   function §\x1d\x1b\t§()
   {
      return this["\x18\x0b\x18"];
   }
   function §\x1b\x11\r§()
   {
      Object.registerClass("GAPILoader",eval("\x19\x04").gapi["\x1e\x1b\x19"].Loader);
      Object.registerClass("UI_MakeReport",dofus["\x1d\x19\x0e"].gapi.ui.MakeReport);
      Object.registerClass("UI_MakeMimibiote",dofus["\x1d\x19\x0e"].gapi.ui.MakeMimibiote);
      Object.registerClass("UI_EditPlayer",dofus["\x1d\x19\x0e"].gapi.ui.EditPlayer);
      Object.registerClass("Label",eval("\x19\x04").gapi["\x1e\x1b\x19"].Label);
      Object.registerClass("ButtonNormalDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonNormalUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonToggleDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonToggleUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonSimpleRectangleUpDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("Button",eval("\x19\x04").gapi["\x1e\x1b\x19"].Button);
      Object.registerClass("SpellsItem",dofus["\x1d\x19\x0e"].gapi.ui.spells.SpellsItem);
      Object.registerClass("BackgroundHidder",eval("\x19\x04").gapi["\x1e\x1b\x19"].BackgroundHidder);
      Object.registerClass("UI_DirectionChooser",dofus["\x1d\x19\x0e"].gapi.ui.DirectionChooser);
      Object.registerClass("ButtonSimpleRectangleUpDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("UI_CardsCollectionContainerHighlight",dofus["\x1d\x19\x0e"].gapi.ui["\x1d\x10\x14"].ContainerHighlight);
      Object.registerClass("UI_CardsCollectionContainerBackground",dofus["\x1d\x19\x0e"].gapi.ui["\x1d\x10\x14"].ContainerBackground);
      Object.registerClass("ButtonMainMenuUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonSpellsUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonCraftUpInvert",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonCraftUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonMainMenuDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonSpellsDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonCraftDownInvert",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonCraftDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("TimelinePointer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1a\f\x18"].TimelinePointer);
      Object.registerClass("DeathCounter",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].DeathCounter);
      Object.registerClass("VerticalChrono",eval("\x19\x04").gapi["\x1e\x1b\x19"].VerticalChrono);
      Object.registerClass("TimelineItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1a\f\x18"].TimelineItem);
      Object.registerClass("ListInventoryViewerItemNoPrice",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1d\x07\x0e"].ListInventoryViewerItemNoPrice);
      Object.registerClass("BookPageIndexChapterItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\r\x03"].BookPageIndexChapterItem);
      Object.registerClass("MountStorageMountItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1c\x1c\x11"].MountStorageMountItem);
      Object.registerClass("ListInventoryViewerItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1d\x07\x0e"].ListInventoryViewerItem);
      Object.registerClass("Window",eval("\x19\x04").gapi["\x1e\x1b\x19"].Window);
      Object.registerClass("ComboBoxNormal",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonComboBoxDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonComboBoxUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ComboBox",eval("\x19\x04").gapi["\x1e\x1b\x19"].ComboBox);
      Object.registerClass("ListInventoryViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ListInventoryViewer);
      Object.registerClass("TextArea",eval("\x19\x04").gapi["\x1e\x1b\x19"].TextArea);
      Object.registerClass("SelectableRow",eval("\x19\x04").gapi["\x1e\x1b\x19"].list.SelectableRow);
      Object.registerClass("DefaultCellRenderer",eval("\x19\x04").gapi["\x1e\x1b\x19"].list.DefaultCellRenderer);
      Object.registerClass("List",eval("\x19\x04").gapi["\x1e\x1b\x19"].List);
      Object.registerClass("ProgressBar",eval("\x19\x04").gapi["\x1e\x1b\x19"].ProgressBar);
      Object.registerClass("ItemViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ItemViewer);
      Object.registerClass("ItemViewerLite",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ItemViewer);
      Object.registerClass("ChooseItemSkin",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ChooseItemSkin);
      Object.registerClass("PlayerWeight",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].PlayerWeight);
      Object.registerClass("UI_PlayerShopModifier",dofus["\x1d\x19\x0e"].gapi.ui.PlayerShopModifier);
      Object.registerClass("UI_TaxCollectorStorage",dofus["\x1d\x19\x0e"].gapi.ui.TaxCollectorStorage);
      Object.registerClass("UI_PlayerShop",dofus["\x1d\x19\x0e"].gapi.ui.PlayerShop);
      Object.registerClass("UI_NpcShop",dofus["\x1d\x19\x0e"].gapi.ui.NpcShop);
      Object.registerClass("DefaultBackground",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\x1e\x1d\x05"].DefaultBackground);
      Object.registerClass("DefaultHighlight",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\x1e\x1d\x05"].DefaultHighlight);
      Object.registerClass("Container",eval("\x19\x04").gapi["\x1e\x1b\x19"].Container);
      Object.registerClass("StylizedRectangle",eval("\x19\x04").gapi["\x1e\x1b\x19"].StylizedRectangle);
      Object.registerClass("ContainerGrid",eval("\x19\x04").gapi["\x1e\x1b\x19"].ContainerGrid);
      Object.registerClass("UI_Inventory",dofus["\x1d\x19\x0e"].gapi.ui.Inventory);
      Object.registerClass("UI_Inventory_TripleFramerate",dofus["\x1d\x19\x0e"].gapi.ui.Inventory);
      Object.registerClass("Timeline",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].Timeline);
      Object.registerClass("UI_Timeline",dofus["\x1d\x19\x0e"].gapi.ui.Timeline);
      Object.registerClass("UI_ChallengeMenu",dofus["\x1d\x19\x0e"].gapi.ui.ChallengeMenu);
      Object.registerClass("UI_StatsJobContainerHighlight",dofus["\x1d\x19\x0e"].gapi.ui["\x1d\x10\x14"].ContainerHighlight);
      Object.registerClass("UI_InventoryContainerHighlight",dofus["\x1d\x19\x0e"].gapi.ui["\x1d\x10\x14"].ContainerHighlight);
      Object.registerClass("UI_InventoryContainerHighlight_TripleFramerate",dofus["\x1d\x19\x0e"].gapi.ui["\x1d\x10\x14"].ContainerHighlight);
      Object.registerClass("UI_ForgemagusContainerHighlight",dofus["\x1d\x19\x0e"].gapi.ui["\x1d\x10\x14"].ContainerHighlight);
      Object.registerClass("UI_StatsJobContainerBackground2",dofus["\x1d\x19\x0e"].gapi.ui["\x1d\x10\x14"].ContainerBackground);
      Object.registerClass("UI_StatsJobContainerBackground",dofus["\x1d\x19\x0e"].gapi.ui["\x1d\x10\x14"].ContainerBackground);
      Object.registerClass("UI_InventoryContainerBackground",dofus["\x1d\x19\x0e"].gapi.ui["\x1d\x10\x14"].ContainerBackground);
      Object.registerClass("UI_ForgemagusContainerBackground",dofus["\x1d\x19\x0e"].gapi.ui["\x1d\x10\x14"].ContainerBackground);
      Object.registerClass("UI_PopupQuantity",dofus["\x1d\x19\x0e"].gapi.ui.PopupQuantity);
      Object.registerClass("UI_PopupQuantityWithDescription",dofus["\x1d\x19\x0e"].gapi.ui.PopupQuantityWithDescription);
      Object.registerClass("UI_PopupHexa",dofus["\x1d\x19\x0e"].gapi.ui.PopupHexa);
      Object.registerClass("UI_StringCourse",dofus["\x1d\x19\x0e"].gapi.ui.StringCourse);
      Object.registerClass("UI_StringCourse_TripleFramerate",dofus["\x1d\x19\x0e"].gapi.ui.StringCourse);
      Object.registerClass("TextInput",eval("\x19\x04").gapi["\x1e\x1b\x19"].TextInput);
      Object.registerClass("ButtonTransparentUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("DataGrid",eval("\x19\x04").gapi["\x1e\x1b\x19"].DataGrid);
      Object.registerClass("UI_Friends",dofus["\x1d\x19\x0e"].gapi.ui.Friends);
      Object.registerClass("UI_FightChallenge",dofus["\x1d\x19\x0e"].gapi.ui.FightChallenge);
      Object.registerClass("FightChallengeIcon",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].FightChallengeIcon);
      Object.registerClass("FightChallengeViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].FightChallengeViewer);
      Object.registerClass("UI_SecureCraft",dofus["\x1d\x19\x0e"].gapi.ui.SecureCraft);
      Object.registerClass("UI_Craft",dofus["\x1d\x19\x0e"].gapi.ui.Craft);
      Object.registerClass("UI_Exchange",dofus["\x1d\x19\x0e"].gapi.ui.Exchange);
      Object.registerClass("UI_AskPrivateChat",dofus["\x1d\x19\x0e"].gapi.ui.AskPrivateChat);
      Object.registerClass("UI_CenterText",dofus["\x1d\x19\x0e"].gapi.ui.CenterText);
      Object.registerClass("UI_CenterInfo",dofus["\x1d\x19\x0e"].gapi.ui.CenterInfo);
      Object.registerClass("UI_AskCancel",dofus["\x1d\x19\x0e"].gapi.ui.AskCancel);
      Object.registerClass("UI_AskLinkWarning",dofus["\x1d\x19\x0e"].gapi.ui.AskLinkWarning);
      Object.registerClass("UI_AskGameBegin",dofus["\x1d\x19\x0e"].gapi.ui.AskGameBegin);
      Object.registerClass("UI_AskGameBegin_TripleFramerate",dofus["\x1d\x19\x0e"].gapi.ui.AskGameBegin);
      Object.registerClass("UI_AskYesNo",dofus["\x1d\x19\x0e"].gapi.ui.AskYesNo);
      Object.registerClass("UI_AskYesNoIgnore",dofus["\x1d\x19\x0e"].gapi.ui.AskYesNoIgnore);
      Object.registerClass("UI_AskCustomShortcut",dofus["\x1d\x19\x0e"].gapi.ui.AskCustomShortcut);
      Object.registerClass("UI_ChooseNickName",dofus["\x1d\x19\x0e"].gapi.ui.ChooseNickName);
      Object.registerClass("UI_AskSecretAnswer",dofus["\x1d\x19\x0e"].gapi.ui.AskSecretAnswer);
      Object.registerClass("UI_AskAlertServer",dofus["\x1d\x19\x0e"].gapi.ui.AskAlertServer);
      Object.registerClass("UI_AskOk",dofus["\x1d\x19\x0e"].gapi.ui.AskOk);
      Object.registerClass("UI_AskOkWait",dofus["\x1d\x19\x0e"].gapi.ui.AskOkWait);
      Object.registerClass("UI_Login",dofus["\x1d\x19\x0e"].gapi.ui.Login);
      Object.registerClass("UI_Login_TripleFramerate",dofus["\x1d\x19\x0e"].gapi.ui.Login);
      Object.registerClass("UI_GameOver",dofus["\x1d\x19\x0e"].gapi.ui.GameOver);
      Object.registerClass("UI_ItemViewer",dofus["\x1d\x19\x0e"].gapi.ui.ItemViewer);
      Object.registerClass("UI_ChooseItemSkin",dofus["\x1d\x19\x0e"].gapi.ui.ChooseItemSkin);
      Object.registerClass("MountViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].MountViewer);
      Object.registerClass("UI_MountViewer",dofus["\x1d\x19\x0e"].gapi.ui.MountViewer);
      Object.registerClass("UI_Mount",dofus["\x1d\x19\x0e"].gapi.ui.Mount);
      Object.registerClass("UI_Temporis",dofus["\x1d\x19\x0e"].gapi.ui.Temporis);
      Object.registerClass("UI_StatsJob",dofus["\x1d\x19\x0e"].gapi.ui.StatsJob);
      Object.registerClass("AlignmentViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].AlignmentViewer);
      Object.registerClass("JobViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].JobViewer);
      Object.registerClass("StatsViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].StatsViewer);
      Object.registerClass("VolumeSlider",eval("\x19\x04").gapi["\x1e\x1b\x19"].VolumeSlider);
      Object.registerClass("JobOptionsViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].JobOptionsViewer);
      Object.registerClass("CraftViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].CraftViewer);
      Object.registerClass("QuestionViewerAnswerItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1b\x13\x1d"].QuestionViewerAnswerItem);
      Object.registerClass("GuildBoostsViewerSpell",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1d\x19\x01"].GuildBoostsViewerSpell);
      Object.registerClass("TaxCollectorsViewerItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1a\x0e\x13"].TaxCollectorsViewerItem);
      Object.registerClass("AlignmentViewerTreeItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1a\x02"].AlignmentViewerTreeItem);
      Object.registerClass("ChooseServerListItem",dofus["\x1d\x19\x0e"].gapi.ui["\x01\x18"].ChooseServerListItem);
      Object.registerClass("UI_JoinFriend",dofus["\x1d\x19\x0e"].gapi.ui.JoinFriend);
      Object.registerClass("UI_JoinFriend_TripleFramerate",dofus["\x1d\x19\x0e"].gapi.ui.JoinFriend);
      Object.registerClass("CraferListItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1e\x1b\b"]["\x1e\x1b\x07"]);
      Object.registerClass("MountParksViewerItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1d\x18\x18"].MountParksViewerItem);
      Object.registerClass("GuildMembersViewerMember",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1d\x18\x19"].GuildMembersViewerMember);
      Object.registerClass("UI_GameResultPlayer",dofus["\x1d\x19\x0e"].gapi.ui["\x1e\t\x17"]["\x1e\t\x16"]);
      Object.registerClass("UI_GameResultPlayerPVP",dofus["\x1d\x19\x0e"].gapi.ui["\x1e\t\x17"].GameResultPlayerPVP);
      Object.registerClass("CraftViewerCraftItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1e\x1a\x1d"].CraftViewerCraftItem);
      Object.registerClass("JobViewerSkillItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1d\x0b\r"].JobViewerSkillItem);
      Object.registerClass("StatsViewerStatItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1a\x12\f"].StatsViewerStatItem);
      Object.registerClass("UI_NpcDialog",dofus["\x1d\x19\x0e"].gapi.ui.NpcDialog);
      Object.registerClass("UI_GameResult",dofus["\x1d\x19\x0e"].gapi.ui.GameResult);
      Object.registerClass("QuestionViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].QuestionViewer);
      Object.registerClass("UI_GameResultTeamPVP",dofus["\x1d\x19\x0e"].gapi.ui["\x1e\t\x17"]["\x1e\t\x15"]);
      Object.registerClass("UI_GameResultTeam",dofus["\x1d\x19\x0e"].gapi.ui["\x1e\t\x17"].GameResultTeam);
      Object.registerClass("UI_FriendsDisconnectedItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1e\n\x0b"]["\x1e\n\t"]);
      Object.registerClass("UI_QuestsStepRewardItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1b\x13\x1a"]["\x1b\x13\x16"]);
      Object.registerClass("UI_BigStorePriceItem",dofus["\x1d\x19\x0e"].gapi.ui.bigstore["\x10\x03"]);
      Object.registerClass("UI_FriendsConnectedItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1e\n\x0b"]["\x1e\n\n"]);
      Object.registerClass("UI_KeyCode",dofus["\x1d\x19\x0e"].gapi.ui.KeyCode);
      Object.registerClass("UI_HouseIndoor",dofus["\x1d\x19\x0e"].gapi.ui.HouseIndoor);
      Object.registerClass("UI_ItemUtility",dofus["\x1d\x19\x0e"].gapi.ui.ItemUtility);
      Object.registerClass("MountWeight",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].MountWeight);
      Object.registerClass("GridInventoryViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].GridInventoryViewer);
      Object.registerClass("UI_Storage",dofus["\x1d\x19\x0e"].gapi.ui.Storage);
      Object.registerClass("UI_Zoom",dofus["\x1d\x19\x0e"].gapi.ui.Zoom);
      Object.registerClass("UI_Tutorial",dofus["\x1d\x19\x0e"].gapi.ui.Tutorial);
      Object.registerClass("UI_MainMenu",dofus["\x1d\x19\x0e"].gapi.ui.MainMenu);
      Object.registerClass("UI_Register",dofus["\x1d\x19\x0e"].gapi.ui.Register);
      Object.registerClass("UI_Options",dofus["\x1d\x19\x0e"].gapi.ui.Options);
      Object.registerClass("UI_AskMainMenu",dofus["\x1d\x19\x0e"].gapi.ui.AskMainMenu);
      Object.registerClass("UI_MountAncestorsViewer",dofus["\x1d\x19\x0e"].gapi.ui.MountAncestorsViewer);
      Object.registerClass("ItemSetViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ItemSetViewer);
      Object.registerClass("LivingItemsViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].LivingItemsViewer);
      Object.registerClass("SpellFullInfosViewerItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1a\x16\x0f"].SpellFullInfosViewerItem);
      Object.registerClass("ItemViewerItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1d\x0b\x18"].ItemViewerItem);
      Object.registerClass("ButtonMuteSoundsDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonMuteMusicDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonMuteSoundsUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonMuteMusicUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("UI_FightOptionButtons",dofus["\x1d\x19\x0e"].gapi.ui.FightOptionButtons);
      Object.registerClass("ChatArea",eval("\x19\x04").gapi["\x1e\x1b\x19"].ChatArea);
      Object.registerClass("Smileys",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].Smileys);
      Object.registerClass("Chat",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].Chat);
      Object.registerClass("CircleChrono",eval("\x19\x04").gapi["\x1e\x1b\x19"].CircleChrono);
      Object.registerClass("ActionPointsViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].PointsViewer);
      Object.registerClass("Heart",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].Heart);
      Object.registerClass("UI_Banner",dofus["\x1d\x19\x0e"].gapi.ui.Banner);
      Object.registerClass("ButtonBannerRoundDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonBannerRoundUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonRadioUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonRadioDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonCheckDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonCheckUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("SpellBoostViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].SpellBoostViewer);
      Object.registerClass("SpellInfosViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].SpellInfosViewer);
      Object.registerClass("UI_Spells",dofus["\x1d\x19\x0e"].gapi.ui.Spells);
      Object.registerClass("UI_MountParkSale",dofus["\x1d\x19\x0e"].gapi.ui.MountParkSale);
      Object.registerClass("UI_HouseSale",dofus["\x1d\x19\x0e"].gapi.ui.HouseSale);
      Object.registerClass("ArtworkRotationItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x17\x11"].ArtworkRotationItem);
      Object.registerClass("ArtworkRotation",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ArtworkRotation);
      Object.registerClass("UI_CreateCharacter",dofus["\x1d\x19\x0e"].gapi.ui.CreateCharacter);
      Object.registerClass("ChooseCharacterSprite",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ChooseCharacterSprite);
      Object.registerClass("UI_ChooseCharacter",dofus["\x1d\x19\x0e"].gapi.ui.ChooseCharacter);
      Object.registerClass("UI_CharactersMigration",dofus["\x1d\x19\x0e"].gapi.ui.CharactersMigration);
      Object.registerClass("UI_CharactersMigrationItem",dofus["\x1d\x19\x0e"].gapi.ui["\x03\x15"].CharactersMigrationItem);
      Object.registerClass("UI_Gifts",dofus["\x1d\x19\x0e"].gapi.ui.Gifts);
      Object.registerClass("UI_ServerList",dofus["\x1d\x19\x0e"].gapi.ui.ServerList);
      Object.registerClass("ChooseServerSprite",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ChooseServerSprite);
      Object.registerClass("UI_ChooseServer",dofus["\x1d\x19\x0e"].gapi.ui.ChooseServer);
      Object.registerClass("ButtonDecorationDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("UI_PlayerInfos",dofus["\x1d\x19\x0e"].gapi.ui.PlayerInfos);
      Object.registerClass("UI_PlayerInfosEffectsItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1b\x17\x0b"]["\x1b\x17\n"]);
      Object.registerClass("UI_WaitingQueue",dofus["\x1d\x19\x0e"].gapi.ui.WaitingQueue);
      Object.registerClass("UI_WaitingMessage",dofus["\x1d\x19\x0e"].gapi.ui.WaitingMessage);
      Object.registerClass("UI_Waiting",dofus["\x1d\x19\x0e"].gapi.ui.Waiting);
      Object.registerClass("UI_Waiting_TripleFramerate",dofus["\x1d\x19\x0e"].gapi.ui.Waiting);
      Object.registerClass("UI_DocumentParchment",dofus["\x1d\x19\x0e"].gapi.ui.DocumentParchment);
      Object.registerClass("UI_DocumentBook",dofus["\x1d\x19\x0e"].gapi.ui.DocumentBook);
      Object.registerClass("UI_Cinematic",dofus["\x1d\x19\x0e"].gapi.ui.Cinematic);
      Object.registerClass("UI_MapInfos",dofus["\x1d\x19\x0e"].gapi.ui.MapInfos);
      Object.registerClass("ClassInfosViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ClassInfosViewer);
      Object.registerClass("ColorPicker",eval("\x19\x04").gapi["\x1e\x1b\x19"].ColorPicker);
      Object.registerClass("ClassCustomize",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ClassCustomize);
      Object.registerClass("ButtonWomanUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonWomanDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonManDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonManUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonArrowDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonArrowUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonColorDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonColorUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonCrossDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonCrossUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonCloseDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonEjectDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonMaximizeDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonMinimizeDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonMoinsDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonPlusDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonCloseUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonEjectUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonMaximizeUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonMinimizeUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonSitUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonSitDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonMoinsUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonPlusUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("BannerSpriteInfos",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].BannerSpriteInfos);
      Object.registerClass("ButtonTabDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonTabUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonTransparentUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("SpouseViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].SpouseViewer);
      Object.registerClass("SpellFullInfosViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].SpellFullInfosViewer);
      Object.registerClass("UI_SpellInfos",dofus["\x1d\x19\x0e"].gapi.ui.SpellInfos);
      Object.registerClass("MapNavigator",eval("\x19\x04").gapi["\x1e\x1b\x19"].MapNavigator);
      Object.registerClass("UI_MapExplorer",dofus["\x1d\x19\x0e"].gapi.ui.MapExplorer);
      Object.registerClass("BookPageText",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].BookPageText);
      Object.registerClass("BookPageIndex",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].BookPageIndex);
      Object.registerClass("BookPageTitle",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].BookPageTitle);
      Object.registerClass("ButtonArrowCornerDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonArrowCornerUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("Emblem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].Emblem);
      Object.registerClass("UI_Guild",dofus["\x1d\x19\x0e"].gapi.ui.Guild);
      Object.registerClass("UI_CreateGuild",dofus["\x1d\x19\x0e"].gapi.ui.CreateGuild);
      Object.registerClass("GuildMountParkViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].GuildMountParkViewer);
      Object.registerClass("TaxCollectorsViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].TaxCollectorsViewer);
      Object.registerClass("GuildBoostsViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].GuildBoostsViewer);
      Object.registerClass("GuildMembersViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].GuildMembersViewer);
      Object.registerClass("UI_CrafterCard",dofus["\x1d\x19\x0e"].gapi.ui.CrafterCard);
      Object.registerClass("UI_GuildMemberInfos",dofus["\x1d\x19\x0e"].gapi.ui.GuildMemberInfos);
      Object.registerClass("ButtonSquareUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonFlatRoundLeft",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonSquareDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonJoinTaxCollectorDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonJoinTaxCollectorUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("TaxCollectorViewerPlayer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1a\x0e\x13"]["\x1a\x0e\x12"]);
      Object.registerClass("UI_Subway",dofus["\x1d\x19\x0e"].gapi.ui.Subway);
      Object.registerClass("UI_MonsterAndLookSelector",dofus["\x1d\x19\x0e"].gapi.ui.MonsterAndLookSelector);
      Object.registerClass("UI_ItemSelector",dofus["\x1d\x19\x0e"].gapi.ui.ItemSelector);
      Object.registerClass("UI_Waypoints",dofus["\x1d\x19\x0e"].gapi.ui.Waypoints);
      Object.registerClass("UI_ShortcutsItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1a\x1e\f"]["\x1a\x1e\x0b"]);
      Object.registerClass("UI_SubwayItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1a\x10\x17"]["\x1a\x10\x16"]);
      Object.registerClass("UI_WaypointsItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1a\x04\x02"]["\x1a\x04\x01"]);
      Object.registerClass("ButtonFlatRoundDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("UI_Buff",dofus["\x1d\x19\x0e"].gapi.ui.Buff);
      Object.registerClass("BuffViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].BuffViewer);
      Object.registerClass("UI_BuffInfos",dofus["\x1d\x19\x0e"].gapi.ui.BuffInfos);
      Object.registerClass("UI_DocumentRoadSignRight",dofus["\x1d\x19\x0e"].gapi.ui.DocumentRoadSign);
      Object.registerClass("UI_DocumentRoadSignLeft",dofus["\x1d\x19\x0e"].gapi.ui.DocumentRoadSign);
      Object.registerClass("SpecializationViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1a\x02"].SpecializationViewer);
      Object.registerClass("RankViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1a\x02"].RankViewer);
      Object.registerClass("AlignmentViewerOrder",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1a\x02"].AlignmentViewerOrder);
      Object.registerClass("AlignmentViewerTree",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1a\x02"].AlignmentViewerTree);
      Object.registerClass("AlignmentViewerFeatsItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1a\x02"].AlignmentViewerFeatsItem);
      Object.registerClass("UI_FightsInfos",dofus["\x1d\x19\x0e"].gapi.ui.FightsInfos);
      Object.registerClass("UI_FightsInfosPlayerItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1e\r\x03"]["\x1e\r\x01"]);
      Object.registerClass("UI_FightsInfosFightItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1e\r\x03"]["\x1e\r\x02"]);
      Object.registerClass("UI_Tips",dofus["\x1d\x19\x0e"].gapi.ui.Tips);
      Object.registerClass("UI_CardsCollection",dofus["\x1d\x19\x0e"].gapi.ui.CardsCollection);
      Object.registerClass("Card",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].Card);
      Object.registerClass("UI_Indicator",dofus["\x1d\x19\x0e"].gapi.ui.Indicator);
      Object.registerClass("UI_ServersManagerRetry",dofus["\x1d\x19\x0e"].gapi.ui.ServersManagerRetry);
      Object.registerClass("UI_Shortcuts",dofus["\x1d\x19\x0e"].gapi.ui.Shortcuts);
      Object.registerClass("UI_Debug",dofus["\x1d\x19\x0e"].gapi.ui.Debug);
      Object.registerClass("UI_Quests",dofus["\x1d\x19\x0e"].gapi.ui.Quests);
      Object.registerClass("UI_PartyItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1b\x18\x19"]["\x1b\x18\x18"]);
      Object.registerClass("UI_Party",dofus["\x1d\x19\x0e"].gapi.ui.Party);
      Object.registerClass("UI_MountStorage",dofus["\x1d\x19\x0e"].gapi.ui.MountStorage);
      Object.registerClass("UI_BigStoreSell",dofus["\x1d\x19\x0e"].gapi.ui.BigStoreSell);
      Object.registerClass("UI_CrafterList",dofus["\x1d\x19\x0e"].gapi.ui.CrafterList);
      Object.registerClass("UI_BigStoreBuy",dofus["\x1d\x19\x0e"].gapi.ui.BigStoreBuy);
      Object.registerClass("UI_BigStoreBuy_TripleFramerate",dofus["\x1d\x19\x0e"].gapi.ui.BigStoreBuy);
      Object.registerClass("UI_BigStoreSearch",dofus["\x1d\x19\x0e"].gapi.ui.BigStoreSearch);
      Object.registerClass("UI_BigStoreSearchFullSoul",dofus["\x1d\x19\x0e"].gapi.ui.BigStoreSearchFullSoul);
      Object.registerClass("UI_InventorySearch",dofus["\x1d\x19\x0e"].gapi.ui.InventorySearch);
      Object.registerClass("UI_QuestsObjectivetItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1b\x13\x1a"]["\x1b\x13\x19"]);
      Object.registerClass("UI_QuestsStepItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1b\x13\x1a"]["\x1b\x13\x17"]);
      Object.registerClass("UI_QuestsQuestItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1b\x13\x1a"]["\x1b\x13\x18"]);
      Object.registerClass("QuestStepViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].QuestStepViewer);
      Object.registerClass("QuestStepListViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].QuestStepListViewer);
      Object.registerClass("UI_PayZoneDialog",dofus["\x1d\x19\x0e"].gapi.ui.PayZoneDialog);
      Object.registerClass("UI_PayZoneDialog2",dofus["\x1d\x19\x0e"].gapi.ui.PayZoneDialog2);
      Object.registerClass("UI_PayZone",dofus["\x1d\x19\x0e"].gapi.ui.PayZone);
      Object.registerClass("UI_PayZone_TripleFramerate",dofus["\x1d\x19\x0e"].gapi.ui.PayZone);
      Object.registerClass("UI_MovableContainerBar",dofus["\x1d\x19\x0e"].gapi.ui.MovableContainerBar);
      Object.registerClass("ButtonSubscribeUp",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("ButtonSubscribeDown",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\b\x11"]["\b\x10"]);
      Object.registerClass("UI_LoginNewsItem",dofus["\x1d\x19\x0e"].gapi.ui.login["\x1d\x05\x0f"]);
      Object.registerClass("UI_GiftsSprite",dofus["\x1d\x19\x0e"].gapi.ui.gifts["\x1d\x1a\x03"]);
      Object.registerClass("GAPIMain",dofus["\x1d\x19\x0e"].gapi["\x1e\t\x14"]);
      Object.registerClass("BATTLEFIELD",dofus["\x1d\x19\x0e"].battlefield["\x1e\x13\x14"]);
      Object.registerClass("ToolTip",eval("\x19\x04").gapi["\x1e\x1b\x19"].ToolTip);
      Object.registerClass("ScrollBarThumb",eval("\x19\x04").gapi["\x1e\x1b\x19"]["\x1b\x0b\x0f"]["\x1b\x0b\b"]);
      Object.registerClass("ScrollBar",eval("\x19\x04").gapi["\x1e\x1b\x19"].ScrollBar);
      Object.registerClass("PopupMenu",eval("\x19\x04").gapi["\x1e\x1b\x19"].PopupMenu);
      Object.registerClass("Fps",eval("\x19\x04").gapi["\x1e\x1b\x19"].Fps);
      Object.registerClass("ConsoleLogger",eval("\x19\x04").gapi["\x1e\x1b\x19"].ConsoleLogger);
      Object.registerClass("Compass",eval("\x19\x04").gapi["\x1e\x1b\x19"].Compass);
      Object.registerClass("Clock",eval("\x19\x04").gapi["\x1e\x1b\x19"].Clock);
      Object.registerClass("MiniMap",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].MiniMap);
      Object.registerClass("SpriteViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].SpriteViewer);
      Object.registerClass("UI_AutomaticServer",dofus["\x1d\x19\x0e"].gapi.ui.AutomaticServer);
      Object.registerClass("UI_AutomaticServer_TripleFramerate",dofus["\x1d\x19\x0e"].gapi.ui.AutomaticServer);
      Object.registerClass("UI_ServerInformations",dofus["\x1d\x19\x0e"].gapi.ui.ServerInformations);
      Object.registerClass("UI_TitleDisplayer",dofus["\x1d\x19\x0e"].gapi.ui.TitleDisplayer);
      Object.registerClass("UI_ForgemagusCraft",dofus["\x1d\x19\x0e"].gapi.ui.ForgemagusCraft);
      Object.registerClass("UI_KnownledgeBase",dofus["\x1d\x19\x0e"].gapi.ui.KnownledgeBase);
      Object.registerClass("UI_KnownledgeBaseCategory",dofus["\x1d\x19\x0e"].gapi.ui["\x1d\n\x18"]["\x1d\n\x17"]);
      Object.registerClass("UI_KnownledgeBaseItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1d\n\x18"]["\x1d\n\x16"]);
      Object.registerClass("Helper",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].Helper);
      Object.registerClass("Helper_TripleFramerate",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].Helper);
      Object.registerClass("UI_FloatingTips",dofus["\x1d\x19\x0e"].gapi.ui.FloatingTips);
      Object.registerClass("MouseShortcuts",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].MouseShortcuts);
      Object.registerClass("ColorSelector",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ColorSelector);
      Object.registerClass("UI_SpellViewerOnCreate",dofus["\x1d\x19\x0e"].gapi.ui.SpellViewerOnCreate);
      Object.registerClass("UI_HistoryViewerOnCreate",dofus["\x1d\x19\x0e"].gapi.ui.HistoryViewerOnCreate);
      Object.registerClass("ClassSelector",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ClassSelector);
      Object.registerClass("UI_GuildHouseRights",dofus["\x1d\x19\x0e"].gapi.ui.GuildHouseRights);
      Object.registerClass("GuildHousesViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].GuildHousesViewer);
      Object.registerClass("GuildHousesViewerHouses",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1d\x18\x1b"].GuildHousesViewerHouses);
      Object.registerClass("UI_ItemSummoner",dofus["\x1d\x19\x0e"].gapi.ui.ItemSummoner);
      Object.registerClass("UI_AskReportMessage",dofus["\x1d\x19\x0e"].gapi.ui.AskReportMessage);
      Object.registerClass("UI_Conquest",dofus["\x1d\x19\x0e"].gapi.ui.Conquest);
      Object.registerClass("ConquestStatsViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ConquestStatsViewer);
      Object.registerClass("ConquestZonesViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ConquestZonesViewer);
      Object.registerClass("ConquestJoinViewer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].ConquestJoinViewer);
      Object.registerClass("UI_SpellForget",dofus["\x1d\x19\x0e"].gapi.ui.SpellForget);
      Object.registerClass("UI_SpellForgetItem",dofus["\x1d\x19\x0e"].gapi.ui["\x1a\x16\x12"]["\x1a\x16\x11"]);
      Object.registerClass("UI_ItemFound",dofus["\x1d\x19\x0e"].gapi.ui.ItemFound);
      Object.registerClass("UI_ChooseFeed",dofus["\x1d\x19\x0e"].gapi.ui.ChooseFeed);
      Object.registerClass("ConquestStatsViewerItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1e\x1c\r"].ConquestStatsViewerItem);
      Object.registerClass("StarsDisplayer",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"].StarsDisplayer);
      Object.registerClass("ConquestZonesViewerAreaItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1e\x1c\t"].ConquestZonesViewerAreaItem);
      Object.registerClass("ConquestZonesViewerVillageItem",dofus["\x1d\x19\x0e"].gapi["\x1e\x1b\x19"]["\x1e\x1c\t"].ConquestZonesViewerVillageItem);
      Object.registerClass("EffectIcon",dofus["\x1d\x19\x0e"].battlefield.EffectIcon);
   }
}
